#!/usr/bin/env python3
# Copyright (c) 2026, Advanced Micro Devices, Inc. All rights reserved.
#
# See LICENSE for license information.
"""JAX FFI inventory (plugin plan S7.2). Static - needs no built extension.

Name-only inventories are not enough on the JAX side for the same reason enum-value
inventories were needed on the torch side: two handlers can share a name and differ in their
attribute schema (the pybind/FFI ``.Attr<T>("name")`` chain), which is exactly the drift a pin
bump can introduce silently. This tool parses, fork and pinned-upstream:

  1. the registration dict in jax/csrc/extensions/pybind.cpp  (te_*_ffi -> Handler symbol)
  2. every ``.Attr<T>("name")`` chain in jax/csrc/extensions/*.cpp, attributed to the
     nearest preceding handler definition (XLA_FFI_DEFINE_HANDLER* / *Handler assignment)

and reports: names missing/extra vs upstream, and per shared name, schema differences.
Exit 1 when the diff does not match jax-ffi-expected-diff.yaml (governed allowlist).
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

import yaml

PROP = Path(__file__).resolve().parents[1]
ROOT = PROP.parent.parent
SUB = "3rdparty/transformer_engine_nvidia"
EXPECT = PROP / "jax-ffi-expected-diff.yaml"


def sh(*a, cwd=ROOT):
    return subprocess.run(a, capture_output=True, text=True, cwd=cwd)


def upstream_files(pin: str) -> dict[str, str]:
    out = {}
    for rel in sh("git", "ls-tree", "-r", "--name-only", pin,
                  "transformer_engine/jax/csrc", cwd=ROOT / SUB).stdout.splitlines():
        if rel.endswith(".cpp"):
            out[rel] = sh("git", "show", f"{pin}:{rel}", cwd=ROOT / SUB).stdout
    return out


def fork_files() -> dict[str, str]:
    out = {}
    for p in (ROOT / "transformer_engine/jax/csrc").rglob("*.cpp"):
        out[str(p.relative_to(ROOT))] = p.read_text(errors="replace")
    return out


# every dict entry, then best-effort handler symbols from its value expression (an entry may
# be a staged pybind11::dict with several EncapsulateFFI(...) handlers - keep them all)
REG_ENTRY = re.compile(r'dict\["(te_\w+)"\]\s*=', re.M)
ENC = re.compile(r"EncapsulateFFI\(\s*(\w+)")
HANDLER_DEF = re.compile(r"XLA_FFI_DEFINE_HANDLER\w*\(\s*(\w+)|^\s*(?:auto|static\s+\w+)?\s*(\w+Handler)\s*=", re.M)
ATTR = re.compile(r'\.\s*(?:Attr|RemainingArgs|Ctx)\s*(?:<([^>]*)>)?\s*\(\s*"?(\w*)"?')


def inventory(files: dict[str, str]) -> dict:
    regs = {}
    for txt in files.values():
        entries = list(REG_ENTRY.finditer(txt))
        for i, m in enumerate(entries):
            end = entries[i + 1].start() if i + 1 < len(entries) else txt.find("return dict", m.end())
            handlers = ENC.findall(txt[m.end(): end if end != -1 else m.end() + 2000])
            regs[m.group(1)] = handlers
    schemas: dict[str, list] = {}
    for txt in files.values():
        # walk handler definitions; collect Attr chains until the statement's closing ');'
        for m in re.finditer(r"XLA_FFI_DEFINE_HANDLER\w*\s*\(\s*(\w+),", txt):
            handler = m.group(1)
            stmt_end = txt.find(";", m.end())
            body = txt[m.end(): stmt_end if stmt_end != -1 else m.end() + 4000]
            attrs = [f"{t or ''}:{n}" for t, n in re.findall(r'\.Attr<([^>]*)>\s*\(\s*"(\w+)"', body)]
            if attrs or handler not in schemas:
                schemas[handler] = attrs
    return {"registrations": regs,
            "schemas": {name: {h: schemas.get(h, []) for h in hs} for name, hs in regs.items()}}


def main() -> int:
    pin = yaml.safe_load(open(PROP / "divergence-manifest.yaml"))["metadata"]["upstream_sha"]
    up = inventory(upstream_files(pin))
    fk = inventory(fork_files())
    up_names, fk_names = set(up["registrations"]), set(fk["registrations"])
    diff = {
        "missing_on_rocm": sorted(up_names - fk_names),
        "rocm_extras": sorted(fk_names - up_names),
        "schema_differs": {},
    }
    for n in sorted(up_names & fk_names):
        if up["schemas"][n] != fk["schemas"][n]:
            diff["schema_differs"][n] = {"upstream": up["schemas"][n], "rocm": fk["schemas"][n]}
    print(f"upstream {len(up_names)} names / fork {len(fk_names)}")
    print(json.dumps(diff, indent=1)[:2400])
    if not EXPECT.exists():
        EXPECT.write_text("# Generated by jax_ffi_inventory.py - review each entry, then this file "
                          "is the governed expectation.\n" + yaml.safe_dump(diff, sort_keys=True))
        print(f"WROTE expectation baseline -> {EXPECT} (review it, then commit)")
        return 0
    expected = yaml.safe_load(EXPECT.read_text())
    if expected != diff:
        print("FFI INVENTORY DRIFT vs jax-ffi-expected-diff.yaml - a pin bump or csrc edit "
              "changed the surface; review and regenerate the expectation deliberately.")
        return 1
    print("matches governed expectation")
    return 0


if __name__ == "__main__":
    sys.exit(main())
