// !!! This is a file automatically generated by hipify!!!
/*************************************************************************
 * Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 *
 * See LICENSE for license information.
 ************************************************************************/

#ifndef TRANSFORMER_ENGINE_LOGGING_H_
#define TRANSFORMER_ENGINE_LOGGING_H_

#include <hip/hip_runtime_api.h>
#include <rocblas.h>
#include <string>
#include <stdexcept>

#define NVTE_ERROR(x) \
    do { \
        throw std::runtime_error(std::string(__FILE__ ":") + std::to_string(__LINE__) +            \
                                 " in function " + __func__ + ": " + x);                           \
    } while (false)

#define NVTE_CHECK(x, ...)                                                                         \
    do {                                                                                           \
        if (!(x)) {                                                                                \
            NVTE_ERROR(std::string("Assertion failed: "  #x ". ") + std::string(__VA_ARGS__));     \
        }                                                                                          \
    } while (false)

namespace {

inline void check_cuda_(hipError_t status) {
    if ( status != hipSuccess ) {
        NVTE_ERROR("CUDA Error: " + std::string(hipGetErrorString(status)));
    }
}

inline void check_cublas_(rocblas_status status) {
    if ( status != rocblas_status_success ) {
        NVTE_ERROR("CUBLAS Error: " + std::string(cublasGetStatusString(status)));
    }
}

}  // namespace

#define NVTE_CHECK_CUDA(ans) { check_cuda_(ans); }

#define NVTE_CHECK_CUBLAS(ans) { check_cublas_(ans); }

#endif  // TRANSFORMER_ENGINE_LOGGING_H_
