[qola]
aiter_commit = "8f816a049449f39609ee7daca8c21d63aa4274ed"    # pinned AITER submodule commit
namespace = "te"
rocm_versions = ["7.2"]

[build]
architectures = ["gfx950", "gfx942"]

[[modules]]
name = "libmha_fwd"
mode = "cpp_itfs"
receipt = 700
drop_srcs = ["mha_fwd_split.cu", "mha_fwd_batch_prefill.cu"]
drop_directions = ["fwd_splitkv", "batch_prefill"]

[[modules]]
name = "libmha_bwd"
mode = "cpp_itfs"
receipt = 700
