[qola]
aiter_commit = "a367904757c88bffb82e7c8b6158ed6774824475"    # pinned AITER submodule commit
namespace = "te"
rocm_versions = ["7.2"]

[build]
architectures = ["gfx950", "gfx942"]

[[modules]]
name = "libmha_fwd"
mode = "cpp_itfs"
receipt = 700
drop_srcs = ["mha_fwd_batch_prefill.cu"]
drop_directions = ["batch_prefill"]

[[modules]]
name = "libmha_bwd"
mode = "cpp_itfs"
receipt = 700
