# Copyright (c) 2025, Advanced Micro Devices, Inc. All rights reserved.
#
# See LICENSE for license information.

# This Dockerfile is used to build TransformerEngine wheels for ROCm on x86_64 architecture
# on top of the manylinux_2_28_x86_64 base image.

# Build args:
# BASE_IMAGE - Base manylinux image to use. Default: quay.io/pypa/manylinux_2_28_x86_64
# ROCM_REPO_URL - ROCm repository URL. Default: https://repo.radeon.com/rocm/rhel8/latest/main/
# GPU_TARGETS - Semicolon separated list of target GPU architectures. Default: "gfx942;gfx950"
# TARGET_BRANCH - Target branch for TransformerEngine. Default: none (use git default)
# GPU_TARGETS and TARGET_BRANCH are passed as environment variables to the resulting image and can be overriden when start a container.

# Set base image
ARG BASE_IMAGE=quay.io/pypa/manylinux_2_28_x86_64
FROM $BASE_IMAGE

ARG ROCM_REPO_URL=https://repo.radeon.com/rocm/rhel8/latest/main/

# Set up ROCm repo
RUN echo -e "[rocm]\nname=ROCm\nbaseurl=${ROCM_REPO_URL}\nenabled=1\ngpgcheck=0" > /etc/yum.repos.d/rocm.repo

# Setup packages
RUN dnf install -y --disablerepo=epel rocm-dev hipblaslt hipblaslt-devel hipcub hipcub-devel
RUN dnf group install -y "Development Tools" && dnf install -y git cmake llvm-toolset gcc-toolset-12

#Uncomment the next line for ROCm 6.4 cmake workaround: remove newer incomnpatible cmake preinstalled on base image
#rm /usr/local/bin/cmake || true 

RUN dnf clean all
RUN rm -rf /var/cache/dnf/*

ENV CMAKE_PREFIX_PATH=/opt/rocm/lib/cmake
ENV NVTE_RELEASE_BUILD=1

ARG GPU_TARGETS="gfx942;gfx950"
ENV NVTE_ROCM_ARCH=${GPU_TARGETS}

ARG TARGET_BRANCH
ENV TARGET_BRANCH=${TARGET_BRANCH}

# Install TransformerEngine
COPY build_wheels.sh /
WORKDIR /TransformerEngine/
RUN git clone https://github.com/ROCm/TransformerEngine.git /TransformerEngine

CMD ["/bin/bash", "/build_wheels.sh", "manylinux_2_28_x86_64", "true", "true", "true", "true"]
