# Copyright (c) 2025-2026, Advanced Micro Devices, Inc. All rights reserved.
#
# See LICENSE for license information.

# This Dockerfile is used to build TransformerEngine wheels for ROCm on x86_64 architecture
# on top of the manylinux_2_28_x86_64 base image.

# Build args:
# BASE_IMAGE - Base manylinux image to use. Default: quay.io/pypa/manylinux_2_28_x86_64
# ROCM_REPO_URL - ROCm TheRock repository URL. Default: https://stable.repo.amd.com/rocm/core/packages/rhel8/x86_64/
# ROCM_DEVEL_PACKAGE - ROCm devel package to install. Default: amdrocm-core-devel10.0-gfx950
# GPU_TARGETS - Semicolon separated list of target GPU architectures. Default: "gfx942;gfx950"
# TARGET_BRANCH - Target branch for TransformerEngine. Default: none (use git default)
# GPU_TARGETS and TARGET_BRANCH can be overriden when start a container with NVTE_ROCM_ARCH and TARGET_BRANCH environment variables.

# Set base image
ARG BASE_IMAGE=quay.io/pypa/manylinux_2_28_x86_64
FROM $BASE_IMAGE

ARG ROCM_REPO_URL=https://stable.repo.amd.com/rocm/core/packages/rhel8/x86_64/
ARG ROCM_DEVEL_PACKAGE=amdrocm-core-devel10.0-gfx950

# Set up ROCm repo
RUN echo -e "[rocm]\nname=ROCm\nbaseurl=${ROCM_REPO_URL}\nenabled=1\ngpgcheck=0" > /etc/yum.repos.d/rocm.repo

# Setup packages
# ROCm TheRock packages are built for single GPU family. However, nothing from HW libraries is statically linked to TE,
# so they can be used to build for multiple GPU targets. Using gfx950 here.
RUN dnf install -y --disablerepo=epel ${ROCM_DEVEL_PACKAGE}

# xz-devel installs lzma needed by AOTriton
# patchelf sets the RUNPATH on the prebuilt ROCm shared objects TE copies in
RUN dnf install -y gcc-toolset-13 xz-devel patchelf

RUN dnf clean all
RUN rm -rf /var/cache/dnf/*

ENV HIP_PLATFORM=amd
ENV ROCM_PATH=/opt/rocm/core

ENV NVTE_RELEASE_BUILD=1

ARG GPU_TARGETS="gfx942;gfx950"
ENV NVTE_ROCM_ARCH=${GPU_TARGETS}

ARG TARGET_BRANCH
ENV TARGET_BRANCH=${TARGET_BRANCH}

# Install TransformerEngine
COPY build_wheels.sh /
WORKDIR /TransformerEngine/
RUN git clone https://github.com/ROCm/TransformerEngine.git /TransformerEngine

CMD ["/bin/bash", "/build_wheels.sh", "manylinux_2_28_x86_64", "true", "true", "true", "true"]
